// Animal definitions for Mofuland Animal Game (動物ゲーム)

export const ANIMALS = [
  {
    id: 0,
    name: 'Hamster',
    nameJa: 'ハムスター',
    radius: 17,
    score: 2,
    color: '#FFB07C',
    gradientColor: '#FFD4B2',
    accentColor: '#D87040',
    eyeColor: '#222222',
    earColor: '#FFB07C',
    innerEarColor: '#FFD1DC',
    type: 'hamster',
  },
  {
    id: 1,
    name: 'Chick',
    nameJa: 'ひよこ',
    radius: 25,
    score: 4,
    color: '#FFE66D',
    gradientColor: '#FFF3B0',
    accentColor: '#E9C46A',
    eyeColor: '#222222',
    beakColor: '#F4A261',
    type: 'chick',
  },
  {
    id: 2,
    name: 'Cat',
    nameJa: 'ねこ',
    radius: 33,
    score: 8,
    color: '#90E0EF',
    gradientColor: '#CAF0F8',
    accentColor: '#00B4D8',
    eyeColor: '#1D3557',
    earColor: '#90E0EF',
    innerEarColor: '#FFB5A7',
    type: 'cat',
  },
  {
    id: 3,
    name: 'Dog',
    nameJa: 'いぬ',
    radius: 41,
    score: 16,
    color: '#E0A96D',
    gradientColor: '#F5D0A9',
    accentColor: '#8C5A2B',
    eyeColor: '#222222',
    earColor: '#8C5A2B',
    type: 'dog',
  },
  {
    id: 4,
    name: 'Rabbit',
    nameJa: 'うさぎ',
    radius: 49,
    score: 32,
    color: '#FFC8DD',
    gradientColor: '#FFE5EC',
    accentColor: '#FF85A1',
    eyeColor: '#4A4A4A',
    earColor: '#FFC8DD',
    innerEarColor: '#FFB5A7',
    type: 'rabbit',
  },
  {
    id: 5,
    name: 'Panda',
    nameJa: 'パンダ',
    radius: 59,
    score: 64,
    color: '#F8F9FA',
    gradientColor: '#FFFFFF',
    accentColor: '#CED4DA',
    eyeColor: '#FFFFFF',
    eyePatchColor: '#212529',
    earColor: '#212529',
    type: 'panda',
  },
  {
    id: 6,
    name: 'Corgi',
    nameJa: 'コーギー',
    radius: 69,
    score: 128,
    color: '#F4A261',
    gradientColor: '#E9C46A',
    accentColor: '#E76F51',
    eyeColor: '#222222',
    earColor: '#E76F51',
    innerEarColor: '#F4A261',
    type: 'corgi',
  },
  {
    id: 7,
    name: 'Otter',
    nameJa: 'カワウソ',
    radius: 81,
    score: 256,
    color: '#B5838D',
    gradientColor: '#E56B6F',
    accentColor: '#6D6875',
    eyeColor: '#222222',
    earColor: '#6D6875',
    type: 'otter',
  },
  {
    id: 8,
    name: 'Alpaca',
    nameJa: 'アルパカ',
    radius: 95,
    score: 512,
    color: '#F4F1DE',
    gradientColor: '#FFFFFF',
    accentColor: '#E07A5F',
    eyeColor: '#3D405B',
    earColor: '#F4F1DE',
    type: 'alpaca',
  },
  {
    id: 9,
    name: 'Capybara',
    nameJa: 'カピバラ',
    radius: 111,
    score: 1024,
    color: '#C19A6B',
    gradientColor: '#E5C07B',
    accentColor: '#8B5A2B',
    eyeColor: '#3D2612',
    earColor: '#8B5A2B',
    type: 'capybara',
  },
  {
    id: 10,
    name: 'Elephant',
    nameJa: 'ゾウ',
    radius: 130,
    score: 2048,
    color: '#A8DADC',
    gradientColor: '#F1FAEE',
    accentColor: '#457B9D',
    eyeColor: '#1D3557',
    earColor: '#457B9D',
    innerEarColor: '#A8DADC',
    type: 'elephant',
  },
];

// Spawning rules: Only animals of tier 0 to 4 can be spawned at top
export const SPAWNABLE_TIERS = [0, 1, 2, 3, 4];

export function getRandomSpawnTier() {
  const weights = [0.40, 0.30, 0.15, 0.10, 0.05];
  const rand = Math.random();
  let cumulative = 0;
  for (let i = 0; i < weights.length; i++) {
    cumulative += weights[i];
    if (rand < cumulative) {
      return i;
    }
  }
  return 0;
}
